Optimize the code a bit. Make it more colorful.

diff --git a/pre-receive b/pre-receive
--- a/pre-receive
+++ b/pre-receive
@@ -4,7 +4,7 @@ CURRENT_REPO_PATH=$(pwd)
 PROJECT_NAME=$(basename "$CURRENT_REPO_PATH")
 ROOT_WORKSPACE="/home/git/gitea-workspace/"
 PROJECT_WORKSPACE="${ROOT_WORKSPACE}/${PROJECT_NAME}"
-COVERAGE_REPORT_FILE="coverage_report.log"
+TESTS_WRAPPER="./tests/run_all_units.sh"
 #######
 #--
 _cleanup() {
@@ -18,19 +18,19 @@ trap _cleanup EXIT
 
 #--
 while read -r _ newrev _
-do  
-    git archive "$newrev" | tar -x -C "${PROJECT_WORKSPACE}"
+do
+    git archive "${newrev}" | tar -x -C "${PROJECT_WORKSPACE}"
 
     pushd "${PROJECT_WORKSPACE}"
-    [[ ! -x ./tests/run_all_units.sh ]] && continue;
-    
-    echo "Preparing to run tests for $newrev ..."
-    ./tests/run_all_units.sh
-    
-    if grep -q FAILURE "${COVERAGE_REPORT_FILE}"; then
-        echo "Failure while running tests on rev $newrev - push denied. Run tests locally and confirm they pass before pushing"
+    [[ ! -x ${TESTS_WRAPPER} ]] && continue;
+
+    echo -e "\n\e[92m[CI]\e[39m Preparing to run tests for \e[92m${newrev}\e[39m ...\n"
+
+    if ! ${TESTS_WRAPPER}; then
+        echo -e "\n\e[92m[CI]\e[39m\e[91m Failure while running tests on rev ${newrev} - push denied.\e[39m\n\e[92m[CI]\e[39m Run tests locally using \e[93m${TESTS_WRAPPER}\e[39m and confirm they pass before pushing."
         exit 1
     fi
 done
+echo -e "\n"
 #-- OK
 exit 0
